### PR TITLE
Fix test

### PR DESCRIPTION
**Pull request by cschneider**

### CODE REVIEW

**Comment by cschneider** [comment]
I found several issues.

1. You used the failsafe plugin which created a second test run
2. You used the old felix scr annotations which are not processed by bnd. I switched one class to show
3. gson 2.8 is not a bundle .. I simply switched back to 2.7. Wrap is a bit difficult to get working
4. I switched to karaf 4.1.0... not sure after all if it is necessary
5. You defined the pax exam stuff in parent. That is not a good idea as it would be added to each module

**Comment by jayeshgarg** [comment]
Hi,

I merged your code with mine and found that now I am unable to see my properties in the Karaf webconsole. I have pushed the updated code here. Please do let me know why.
Thanks
Regards

**Comment by cschneider** [comment]
Not sure what you mean? Can you explain a bit what (and where) you saw on the webconsole before and what you see now?  Was it during a test run or in normal deployment?

**Comment by jayeshgarg** [comment]
So here's the process:-
I installed following features = war, http(in manual deployment), pax-http(IT deployment), scr and "webconsole" in karaf 3.0.8 ( I am having Java 1.7 and currently can't move to 1.8)
I deployed all the relevant bundles and my project bundles.

Now I launched "karaf.bat" which deployed jetty container as well.

Now go to "http://localhost:8181/system/console/" login into console

goto OSGi->Configuration

Here previously I was able to see my configurable properties (eg. readInterval in WeatherStationImpl.java) but after changes, I am not able to see that in console.

**Pull request closed without merging**
